package RemCalcApp;


/**
* RemCalcApp/RemCalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemCalc.idl
* Segunda-feira, 28 de Setembro de 2015 00h09min11s AMT
*/

public interface RemCalcOperations 
{
  String calculate (String expr);
  void shutdown ();
} // interface RemCalcOperations
