package RemCalcApp;


/**
* RemCalcApp/RemCalcHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemCalc.idl
* Domingo, 27 de Setembro de 2015 21h48min43s AMT
*/

abstract public class RemCalcHelper
{
  private static String  _id = "IDL:RemCalcApp/RemCalc:1.0";

  public static void insert (org.omg.CORBA.Any a, RemCalcApp.RemCalc that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RemCalcApp.RemCalc extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RemCalcApp.RemCalcHelper.id (), "RemCalc");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RemCalcApp.RemCalc read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RemCalcStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RemCalcApp.RemCalc value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RemCalcApp.RemCalc narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RemCalcApp.RemCalc)
      return (RemCalcApp.RemCalc)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RemCalcApp._RemCalcStub stub = new RemCalcApp._RemCalcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RemCalcApp.RemCalc unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RemCalcApp.RemCalc)
      return (RemCalcApp.RemCalc)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RemCalcApp._RemCalcStub stub = new RemCalcApp._RemCalcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
