package RemCalcApp;

/**
* RemCalcApp/RemCalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemCalc.idl
* Domingo, 27 de Setembro de 2015 17h59min46s AMT
*/

public final class RemCalcHolder implements org.omg.CORBA.portable.Streamable
{
  public RemCalcApp.RemCalc value = null;

  public RemCalcHolder ()
  {
  }

  public RemCalcHolder (RemCalcApp.RemCalc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RemCalcApp.RemCalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RemCalcApp.RemCalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RemCalcApp.RemCalcHelper.type ();
  }

}
