package RemCalcApp;


/**
* RemCalcApp/RemCalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemCalc.idl
* Domingo, 27 de Setembro de 2015 21h48min43s AMT
*/

public interface RemCalcOperations 
{
  double calculate (String expr);
  void shutdown ();
} // interface RemCalcOperations
