package RemCalcApp;


/**
* RemCalcApp/RemCalc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemCalc.idl
* Domingo, 27 de Setembro de 2015 17h59min46s AMT
*/

public interface RemCalc extends RemCalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RemCalc
