package RemCalcApp;


/**
* RemCalcApp/RemCalcPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemCalc.idl
* Domingo, 27 de Setembro de 2015 20h09min47s AMT
*/

public abstract class RemCalcPOA extends org.omg.PortableServer.Servant
 implements RemCalcApp.RemCalcOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calculate", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // RemCalcApp/RemCalc/calculate
       {
         String expr = in.read_string ();
         double $result = (double)0;
         $result = this.calculate (expr);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // RemCalcApp/RemCalc/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RemCalcApp/RemCalc:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RemCalc _this() 
  {
    return RemCalcHelper.narrow(
    super._this_object());
  }

  public RemCalc _this(org.omg.CORBA.ORB orb) 
  {
    return RemCalcHelper.narrow(
    super._this_object(orb));
  }


} // class RemCalcPOA
